# Generated by Django 4.2 on 2025-12-23 12:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Descriptive name for this endpoint", max_length=255)),
                ("url", models.URLField(help_text="Webhook URL to receive events")),
                ("secret", models.CharField(blank=True, help_text="HMAC secret for signing payloads", max_length=255)),
                ("event_types", models.JSONField(default=list, help_text="List of event types to send")),
                ("headers", models.JSONField(blank=True, default=dict, help_text="Additional headers to include")),
                ("is_active", models.BooleanField(default=True)),
                ("max_retries", models.IntegerField(default=3)),
                ("retry_delay_seconds", models.IntegerField(default=60)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("last_status_code", models.IntegerField(blank=True, null=True)),
                ("failure_count", models.IntegerField(default=0)),
                ("circuit_open_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "webhook endpoint",
                "verbose_name_plural": "webhook endpoints",
                "db_table": "webhook_endpoints",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("payload", models.JSONField(default=dict)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        help_text="Unique key to prevent duplicate webhook processing",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("dlq", "Dead Letter Queue"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("attempt_count", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=5)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sla_deadline",
                    models.DateTimeField(
                        blank=True, help_text="Deadline for successful delivery (for SLA reporting)", null=True
                    ),
                ),
                ("sla_met", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("moved_to_dlq_at", models.DateTimeField(blank=True, null=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="webhooks.webhookendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "webhook delivery",
                "verbose_name_plural": "webhook deliveries",
                "db_table": "webhook_deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeadLetterQueue",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("max_retries", "Maximum retries exceeded"),
                            ("circuit_breaker", "Circuit breaker open"),
                            ("invalid_endpoint", "Invalid endpoint"),
                            ("payload_error", "Payload serialization error"),
                            ("timeout", "Request timeout"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("error_details", models.TextField(blank=True)),
                ("reprocessed", models.BooleanField(default=False)),
                ("reprocessed_at", models.DateTimeField(blank=True, null=True)),
                ("reprocess_result", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "original_delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dlq_entry",
                        to="webhooks.webhookdelivery",
                    ),
                ),
            ],
            options={
                "verbose_name": "dead letter entry",
                "verbose_name_plural": "dead letter entries",
                "db_table": "webhook_dead_letter_queue",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["event_type"], name="webhook_del_event_t_a1b2c3_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["status"], name="webhook_del_status_c0d123_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["created_at"], name="webhook_del_created_123456_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["idempotency_key"], name="webhook_del_idempot_789012_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["next_retry_at"], name="webhook_del_next_re_345678_idx"),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(fields=["sla_deadline"], name="webhook_del_sla_dea_901234_idx"),
        ),
    ]
