apiVersion: v1
kind: Service
metadata:
  name: securesys-backend
  namespace: securesys
  labels:
    app.kubernetes.io/name: securesys-auditor
    app.kubernetes.io/component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  type: ClusterIP
  selector:
    app: securesys-backend
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
