apiVersion: v1
kind: Service
metadata:
  name: securesys-frontend
  namespace: securesys
  labels:
    app.kubernetes.io/name: securesys-auditor
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app: securesys-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
