# Generated by Django 4.2.27 on 2025-12-26 16:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Finding",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("access_control", "Access Control"),
                            ("configuration", "Configuration"),
                            ("patch_management", "Patch Management"),
                            ("network", "Network"),
                            ("authentication", "Authentication"),
                            ("encryption", "Encryption"),
                            ("logging", "Logging"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("evidence", models.JSONField(default=dict)),
                ("cwe_id", models.CharField(blank=True, help_text="CWE ID if applicable", max_length=20)),
                ("cvss_score", models.FloatField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "finding",
                "verbose_name_plural": "findings",
                "db_table": "scanning_findings",
                "ordering": ["-severity", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("hostname", models.CharField(db_index=True, max_length=255)),
                ("os", models.CharField(max_length=255, verbose_name="Operating System")),
                ("os_version", models.CharField(blank=True, max_length=100)),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("development", "Development"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                            ("testing", "Testing"),
                        ],
                        default="development",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("latest_risk_score", models.IntegerField(blank=True, null=True)),
                ("latest_maturity_level", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "verbose_name": "system",
                "verbose_name_plural": "systems",
                "db_table": "scanning_systems",
                "ordering": ["-last_seen", "hostname"],
                "indexes": [
                    models.Index(fields=["hostname"], name="scanning_sy_hostnam_010eb6_idx"),
                    models.Index(fields=["environment"], name="scanning_sy_environ_da8275_idx"),
                    models.Index(fields=["last_seen"], name="scanning_sy_last_se_0e3da9_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Scan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Scan"),
                            ("quick", "Quick Scan"),
                            ("compliance", "Compliance Scan"),
                            ("vulnerability", "Vulnerability Scan"),
                        ],
                        default="full",
                        max_length=20,
                    ),
                ),
                ("scan_date", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("risk_score", models.IntegerField(blank=True, help_text="Risk score from 0-100", null=True)),
                (
                    "maturity_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("reactive", "Reactive"),
                            ("basic", "Basic"),
                            ("managed", "Managed"),
                            ("optimized", "Optimized"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scan_payload", models.JSONField(default=dict)),
                ("score_breakdown", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="scans", to="scanning.system"
                    ),
                ),
            ],
            options={
                "verbose_name": "scan",
                "verbose_name_plural": "scans",
                "db_table": "scanning_scans",
                "ordering": ["-scan_date"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "effort",
                    models.CharField(
                        choices=[
                            ("low", "Low (< 1 hour)"),
                            ("medium", "Medium (1-4 hours)"),
                            ("high", "High (4+ hours)"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("steps", models.JSONField(default=list)),
                ("script_bash", models.TextField(blank=True)),
                ("script_powershell", models.TextField(blank=True)),
                ("script_ansible", models.TextField(blank=True)),
                ("references", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="scanning.finding",
                    ),
                ),
            ],
            options={
                "verbose_name": "recommendation",
                "verbose_name_plural": "recommendations",
                "db_table": "scanning_recommendations",
                "ordering": ["-priority", "effort"],
            },
        ),
        migrations.AddField(
            model_name="finding",
            name="scan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="findings", to="scanning.scan"
            ),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(fields=["scan_date"], name="scanning_sc_scan_da_60522d_idx"),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(fields=["status"], name="scanning_sc_status_e23654_idx"),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(fields=["system", "scan_date"], name="scanning_sc_system__3c1bd9_idx"),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(fields=["severity"], name="scanning_fi_severit_f06e1a_idx"),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(fields=["category"], name="scanning_fi_categor_255421_idx"),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(fields=["scan", "severity"], name="scanning_fi_scan_id_a5999d_idx"),
        ),
    ]
