# Generated by Django 4.2.27 on 2025-12-26 16:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("email", models.EmailField(db_index=True, max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                (
                    "role",
                    models.CharField(
                        choices=[("viewer", "Viewer"), ("auditor", "Auditor"), ("admin", "Admin")],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "db_table": "users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("access_control", "Access Control"),
                            ("configuration", "Configuration"),
                            ("patch_management", "Patch Management"),
                            ("network", "Network"),
                            ("authentication", "Authentication"),
                            ("encryption", "Encryption"),
                            ("logging", "Logging"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("evidence", models.JSONField(default=dict)),
                ("cwe_id", models.CharField(blank=True, help_text="CWE ID if applicable", max_length=20)),
                ("cvss_score", models.FloatField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "finding",
                "verbose_name_plural": "findings",
                "db_table": "findings",
                "ordering": ["-severity", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Scan",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("scan_date", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("risk_score", models.IntegerField(blank=True, help_text="Risk score from 0-100", null=True)),
                (
                    "maturity_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("reactive", "Reactive"),
                            ("basic", "Basic"),
                            ("managed", "Managed"),
                            ("optimized", "Optimized"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scan_payload", models.JSONField(default=dict)),
                ("score_breakdown", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "scan",
                "verbose_name_plural": "scans",
                "db_table": "scans",
                "ordering": ["-scan_date"],
            },
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("hostname", models.CharField(db_index=True, max_length=255)),
                ("os", models.CharField(max_length=255, verbose_name="Operating System")),
                ("os_version", models.CharField(blank=True, max_length=100)),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("development", "Development"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                            ("testing", "Testing"),
                        ],
                        default="development",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("latest_risk_score", models.IntegerField(blank=True, null=True)),
                ("latest_maturity_level", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "verbose_name": "system",
                "verbose_name_plural": "systems",
                "db_table": "systems",
                "ordering": ["-last_seen", "hostname"],
                "indexes": [
                    models.Index(fields=["hostname"], name="systems_hostnam_8dbb20_idx"),
                    models.Index(fields=["environment"], name="systems_environ_83cff8_idx"),
                    models.Index(fields=["last_seen"], name="systems_last_se_d34378_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityMaturityAssessment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "overall_level",
                    models.IntegerField(
                        choices=[
                            (1, "Level 1 - Initial/Ad Hoc"),
                            (2, "Level 2 - Developing"),
                            (3, "Level 3 - Defined"),
                            (4, "Level 4 - Managed/Optimized"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "identity_access_score",
                    models.IntegerField(default=1, help_text="Identity & Access Management maturity"),
                ),
                ("asset_management_score", models.IntegerField(default=1, help_text="Asset Management maturity")),
                ("data_security_score", models.IntegerField(default=1, help_text="Data Security & Privacy maturity")),
                (
                    "vulnerability_mgmt_score",
                    models.IntegerField(default=1, help_text="Vulnerability Management maturity"),
                ),
                (
                    "configuration_mgmt_score",
                    models.IntegerField(default=1, help_text="Configuration Management maturity"),
                ),
                ("incident_response_score", models.IntegerField(default=1, help_text="Incident Response maturity")),
                ("monitoring_logging_score", models.IntegerField(default=1, help_text="Monitoring & Logging maturity")),
                ("network_security_score", models.IntegerField(default=1, help_text="Network Security maturity")),
                ("nist_identify_score", models.IntegerField(default=1, help_text="NIST Identify function score")),
                ("nist_protect_score", models.IntegerField(default=1, help_text="NIST Protect function score")),
                ("nist_detect_score", models.IntegerField(default=1, help_text="NIST Detect function score")),
                ("nist_respond_score", models.IntegerField(default=1, help_text="NIST Respond function score")),
                ("nist_recover_score", models.IntegerField(default=1, help_text="NIST Recover function score")),
                (
                    "assessment_details",
                    models.JSONField(default=dict, help_text="Detailed control-by-control assessment results"),
                ),
                (
                    "improvement_roadmap",
                    models.JSONField(default=list, help_text="Prioritized improvement recommendations"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="maturity_assessment", to="core.scan"
                    ),
                ),
            ],
            options={
                "verbose_name": "security maturity assessment",
                "verbose_name_plural": "security maturity assessments",
                "db_table": "security_maturity_assessments",
            },
        ),
        migrations.AddField(
            model_name="scan",
            name="system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="scans", to="core.system"
            ),
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "effort",
                    models.CharField(
                        choices=[
                            ("low", "Low (< 1 hour)"),
                            ("medium", "Medium (1-4 hours)"),
                            ("high", "High (4+ hours)"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("steps", models.JSONField(default=list)),
                ("script_bash", models.TextField(blank=True)),
                ("script_powershell", models.TextField(blank=True)),
                ("script_ansible", models.TextField(blank=True)),
                ("references", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="recommendations", to="core.finding"
                    ),
                ),
            ],
            options={
                "verbose_name": "recommendation",
                "verbose_name_plural": "recommendations",
                "db_table": "recommendations",
                "ordering": ["-priority", "effort"],
            },
        ),
        migrations.AddField(
            model_name="finding",
            name="scan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="findings", to="core.scan"
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "User Login"),
                            ("LOGOUT", "User Logout"),
                            ("CREATE_SYSTEM", "System Created"),
                            ("UPDATE_SYSTEM", "System Updated"),
                            ("DELETE_SYSTEM", "System Deleted"),
                            ("SUBMIT_SCAN", "Scan Submitted"),
                            ("VIEW_SCAN", "Scan Viewed"),
                            ("GENERATE_REPORT", "Report Generated"),
                            ("UPDATE_FINDING", "Finding Updated"),
                            ("USER_CREATED", "User Created"),
                            ("USER_UPDATED", "User Updated"),
                            ("ROLE_CHANGED", "User Role Changed"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("resource_type", models.CharField(blank=True, max_length=50)),
                ("resource_id", models.UUIDField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "audit log",
                "verbose_name_plural": "audit logs",
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "managed": True,
            },
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(fields=["scan_date"], name="scans_scan_da_a037e8_idx"),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(fields=["status"], name="scans_status_dc5ad7_idx"),
        ),
        migrations.AddIndex(
            model_name="scan",
            index=models.Index(fields=["system", "scan_date"], name="scans_system__72ec4e_idx"),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(fields=["severity"], name="findings_severit_c2e745_idx"),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(fields=["category"], name="findings_categor_5fd8a9_idx"),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(fields=["scan", "severity"], name="findings_scan_id_8f361b_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["timestamp"], name="audit_logs_timesta_423be6_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action"], name="audit_logs_action_31f574_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["user", "timestamp"], name="audit_logs_user_id_88267f_idx"),
        ),
    ]
