apiVersion: v1
kind: Namespace
metadata:
  name: securesys
  labels:
    app.kubernetes.io/name: securesys-auditor
    app.kubernetes.io/part-of: securesys
    # Enable Istio sidecar injection if using service mesh
    # istio-injection: enabled
